[project]
name = "railway-signals"
version = "1.0.0"
authors = [{ name = "Jan Graichen", email = "jgraichen@altimos.de" }]
dependencies = [
    "mkdocs-material>=9.5.25",
]
requires-python = "==3.12.*"
readme = "README.md"

[tool.pdm]
distribution = false
